import DiscreteDifferentialGeometryCanonicalLaneLean.Basic
import DiscreteDifferentialGeometryCanonicalLaneLean.SourcePackage
import DiscreteDifferentialGeometryCanonicalLaneLean.SourceDependencies
import DiscreteDifferentialGeometryCanonicalLaneLean.Formalization
import DiscreteDifferentialGeometryCanonicalLaneLean.ReviewerBridge
import DiscreteDifferentialGeometryCanonicalLaneLean.TheoremStatement
import DiscreteDifferentialGeometryCanonicalLaneLean.MathlibObjects
import DiscreteDifferentialGeometryCanonicalLaneLean.AdmissibleClass
import DiscreteDifferentialGeometryCanonicalLaneLean.BridgeLemmas
import DiscreteDifferentialGeometryCanonicalLaneLean.GateLemmas
import DiscreteDifferentialGeometryCanonicalLaneLean.FinalTheorem
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteConnection
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteCurvature
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteParallelTransport
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteHolonomy
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteGeodesics
import DiscreteDifferentialGeometryCanonicalLaneLean.DiscreteExteriorCalculus

namespace HautevilleHouse
namespace DiscreteDifferentialGeometryCanonicalLaneLean

-- root module marker
theorem discrete_differential_geometry_canonical_lane_lean_imported : True := True.intro

end DiscreteDifferentialGeometryCanonicalLaneLean
end HautevilleHouse
